// 自动生成：scripts/update_models.py —— 勿手改。
// 数据源：https://models.dev/api.json（LLM 过滤：output 含 text 且不含 audio/video）
// 快照时间（UTC）：2026-07-31 14:08:37     provider：deepseek, openai, anthropic, google
// 重新生成：python scripts/update_models.py
#pragma once

#include <array>
#include <optional>
#include <string_view>
#include <agent/llm.hpp>

namespace agent::detail {

inline constexpr BuiltinModel kGeneratedModels[] = {
    // ── deepseek（4 个 LLM）──
    {
        .id = "deepseek-chat",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "deepseek-reasoner",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "deepseek-v4-flash",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, "high", std::nullopt, "max" },
        .thinking_field = {},
    },
    {
        .id = "deepseek-v4-pro",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, "high", std::nullopt, "max" },
        .thinking_field = {},
    },
    // ── openai（44 个 LLM）──
    {
        .id = "chatgpt-image-latest",
        .context_window = 0,
        .max_output_tokens = 0,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-3.5-turbo",
        .context_window = 16385,
        .max_output_tokens = 4096,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4",
        .context_window = 8192,
        .max_output_tokens = 8192,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4-turbo",
        .context_window = 128000,
        .max_output_tokens = 4096,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4.1",
        .context_window = 1047576,
        .max_output_tokens = 32768,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4.1-mini",
        .context_window = 1047576,
        .max_output_tokens = 32768,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4.1-nano",
        .context_window = 1047576,
        .max_output_tokens = 32768,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4o",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4o-2024-05-13",
        .context_window = 128000,
        .max_output_tokens = 4096,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4o-2024-08-06",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4o-2024-11-20",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-4o-mini",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5-mini",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5-nano",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5-pro",
        .context_window = 400000,
        .max_output_tokens = 272000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.1",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.2",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.2-chat-latest",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, "medium", std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.2-pro",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.3-chat-latest",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.3-codex",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.3-codex-spark",
        .context_window = 128000,
        .max_output_tokens = 32000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.4",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.4-mini",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.4-nano",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.4-pro",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.5",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.5-pro",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, "medium", "high", "xhigh", std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.6",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.6-luna",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.6-sol",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "gpt-5.6-terra",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "gpt-image-1-mini",
        .context_window = 0,
        .max_output_tokens = 0,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gpt-image-1.5",
        .context_window = 0,
        .max_output_tokens = 0,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "o1",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "o1-pro",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "o3",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "o3-mini",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "o3-pro",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "o4-mini",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "text-embedding-3-large",
        .context_window = 8191,
        .max_output_tokens = 3072,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "text-embedding-3-small",
        .context_window = 8191,
        .max_output_tokens = 1536,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "text-embedding-ada-002",
        .context_window = 8192,
        .max_output_tokens = 1536,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    // ── anthropic（15 个 LLM）──
    {
        .id = "claude-fable-5",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "claude-haiku-4-5",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-haiku-4-5-20251001",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-1",
        .context_window = 200000,
        .max_output_tokens = 32000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-1-20250805",
        .context_window = 200000,
        .max_output_tokens = 32000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-5",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-5-20251101",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-6",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, "max" },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-7",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-4-8",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "claude-opus-5",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    {
        .id = "claude-sonnet-4-5",
        .context_window = 1000000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-sonnet-4-5-20250929",
        .context_window = 1000000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "claude-sonnet-4-6",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, "max" },
        .thinking_field = {},
    },
    {
        .id = "claude-sonnet-5",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
    },
    // ── google（30 个 LLM）──
    {
        .id = "deep-research-max-preview-04-2026",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "deep-research-preview-04-2026",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.0-flash",
        .context_window = 1048576,
        .max_output_tokens = 8192,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.0-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 8192,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.5-computer-use-preview-10-2025",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.5-flash",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.5-flash-image",
        .context_window = 32768,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.5-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-2.5-pro",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3-flash-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3-pro-image",
        .context_window = 131072,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", std::nullopt, "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3-pro-image-preview",
        .context_window = 131072,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3-pro-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", std::nullopt, "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-flash-image",
        .context_window = 65536,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", std::nullopt, std::nullopt, "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-flash-image-preview",
        .context_window = 65536,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", std::nullopt, std::nullopt, "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-flash-lite-image",
        .context_window = 65536,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", std::nullopt, std::nullopt, "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-flash-lite-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-pro-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.1-pro-preview-customtools",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.5-flash",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.5-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-3.6-flash",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-embedding-001",
        .context_window = 2048,
        .max_output_tokens = 1,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-embedding-2",
        .context_window = 8192,
        .max_output_tokens = 1,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-flash-latest",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-flash-lite-latest",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, "minimal", "low", "medium", "high", std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemini-robotics-er-1.6-preview",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemma-4-26b-a4b-it",
        .context_window = 262144,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
    {
        .id = "gemma-4-31b-it",
        .context_window = 262144,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
    },
};

inline constexpr BuiltinProviderTable kAllProviders[] = {
    { "deepseek", std::span<const BuiltinModel>(&kGeneratedModels[0], 4) },
    { "openai", std::span<const BuiltinModel>(&kGeneratedModels[4], 44) },
    { "anthropic", std::span<const BuiltinModel>(&kGeneratedModels[48], 15) },
    { "google", std::span<const BuiltinModel>(&kGeneratedModels[63], 30) },
};

}  // namespace agent::detail
