// 自动生成：scripts/update_models.py —— 勿手改。
// 数据源：https://models.dev/api.json（LLM 过滤：output 含 text 且不含 audio/video）
// 快照时间（UTC）：2026-08-01 04:42:00     provider：deepseek, openai, anthropic, google
// 重新生成：python scripts/update_models.py
#pragma once

#include <optional>
#include <span>
#include <agent/llm/model.hpp>

namespace agent::detail {

inline constexpr BuiltinModel kGeneratedModels[] = {
    // ── deepseek（4 个 LLM）──
    {
        .id = "deepseek-chat",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.14,
        .price_output = 0.28,
        .price_cache_read = 0.0028,
        .price_cache_write = 0.0,
    },
    {
        .id = "deepseek-reasoner",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 0.14,
        .price_output = 0.28,
        .price_cache_read = 0.0028,
        .price_cache_write = 0.0,
    },
    {
        .id = "deepseek-v4-flash",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { "off", "high", "high", "high", "high", "high", "max" },
        .thinking_field = {},
        .price_input = 0.14,
        .price_output = 0.28,
        .price_cache_read = 0.0028,
        .price_cache_write = 0.0,
    },
    {
        .id = "deepseek-v4-pro",
        .context_window = 1000000,
        .max_output_tokens = 384000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { "off", "high", "high", "high", "high", "high", "max" },
        .thinking_field = {},
        .price_input = 0.435,
        .price_output = 0.87,
        .price_cache_read = 0.003625,
        .price_cache_write = 0.0,
    },
    // ── openai（44 个 LLM）──
    {
        .id = "chatgpt-image-latest",
        .context_window = 0,
        .max_output_tokens = 0,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.0,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-3.5-turbo",
        .context_window = 16385,
        .max_output_tokens = 4096,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.5,
        .price_output = 1.5,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4",
        .context_window = 8192,
        .max_output_tokens = 8192,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 30.0,
        .price_output = 60.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4-turbo",
        .context_window = 128000,
        .max_output_tokens = 4096,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 10.0,
        .price_output = 30.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4.1",
        .context_window = 1047576,
        .max_output_tokens = 32768,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 8.0,
        .price_cache_read = 0.5,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4.1-mini",
        .context_window = 1047576,
        .max_output_tokens = 32768,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.4,
        .price_output = 1.6,
        .price_cache_read = 0.1,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4.1-nano",
        .context_window = 1047576,
        .max_output_tokens = 32768,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.1,
        .price_output = 0.4,
        .price_cache_read = 0.025,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4o",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 2.5,
        .price_output = 10.0,
        .price_cache_read = 1.25,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4o-2024-05-13",
        .context_window = 128000,
        .max_output_tokens = 4096,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 15.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4o-2024-08-06",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 2.5,
        .price_output = 10.0,
        .price_cache_read = 1.25,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4o-2024-11-20",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 2.5,
        .price_output = 10.0,
        .price_cache_read = 1.25,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-4o-mini",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.15,
        .price_output = 0.6,
        .price_cache_read = 0.075,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.25,
        .price_output = 10.0,
        .price_cache_read = 0.125,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5-mini",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.25,
        .price_output = 2.0,
        .price_cache_read = 0.025,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5-nano",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.05,
        .price_output = 0.4,
        .price_cache_read = 0.005,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5-pro",
        .context_window = 400000,
        .max_output_tokens = 272000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "high", "high", "high", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 15.0,
        .price_output = 120.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.1",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.25,
        .price_output = 10.0,
        .price_cache_read = 0.125,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.2",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 1.75,
        .price_output = 14.0,
        .price_cache_read = 0.175,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.2-chat-latest",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "medium", "medium", "medium", "medium", "medium", "medium" },
        .thinking_field = {},
        .price_input = 1.75,
        .price_output = 14.0,
        .price_cache_read = 0.175,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.2-pro",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "medium", "medium", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 21.0,
        .price_output = 168.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.3-chat-latest",
        .context_window = 128000,
        .max_output_tokens = 16384,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 1.75,
        .price_output = 14.0,
        .price_cache_read = 0.175,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.3-codex",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 1.75,
        .price_output = 14.0,
        .price_cache_read = 0.175,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.3-codex-spark",
        .context_window = 128000,
        .max_output_tokens = 32000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 1.75,
        .price_output = 14.0,
        .price_cache_read = 0.175,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.4",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 2.5,
        .price_output = 15.0,
        .price_cache_read = 0.25,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.4-mini",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 0.75,
        .price_output = 4.5,
        .price_cache_read = 0.075,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.4-nano",
        .context_window = 400000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 0.2,
        .price_output = 1.25,
        .price_cache_read = 0.02,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.4-pro",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "medium", "medium", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 30.0,
        .price_output = 180.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.5",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 30.0,
        .price_cache_read = 0.5,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.5-pro",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "medium", "medium", "medium", "high", "xhigh", "xhigh" },
        .thinking_field = {},
        .price_input = 30.0,
        .price_output = 180.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-5.6",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 30.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "gpt-5.6-luna",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 0.2,
        .price_output = 1.2,
        .price_cache_read = 0.02,
        .price_cache_write = 0.25,
    },
    {
        .id = "gpt-5.6-sol",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 30.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "gpt-5.6-terra",
        .context_window = 1050000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 12.0,
        .price_cache_read = 0.2,
        .price_cache_write = 2.5,
    },
    {
        .id = "gpt-image-1-mini",
        .context_window = 0,
        .max_output_tokens = 0,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.0,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gpt-image-1.5",
        .context_window = 0,
        .max_output_tokens = 0,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.0,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "o1",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 15.0,
        .price_output = 60.0,
        .price_cache_read = 7.5,
        .price_cache_write = 0.0,
    },
    {
        .id = "o1-pro",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 150.0,
        .price_output = 600.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "o3",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 8.0,
        .price_cache_read = 0.5,
        .price_cache_write = 0.0,
    },
    {
        .id = "o3-mini",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = false,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.1,
        .price_output = 4.4,
        .price_cache_read = 0.55,
        .price_cache_write = 0.0,
    },
    {
        .id = "o3-pro",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 20.0,
        .price_output = 80.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "o4-mini",
        .context_window = 200000,
        .max_output_tokens = 100000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.1,
        .price_output = 4.4,
        .price_cache_read = 0.275,
        .price_cache_write = 0.0,
    },
    {
        .id = "text-embedding-3-large",
        .context_window = 8191,
        .max_output_tokens = 3072,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.13,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "text-embedding-3-small",
        .context_window = 8191,
        .max_output_tokens = 1536,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.02,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "text-embedding-ada-002",
        .context_window = 8192,
        .max_output_tokens = 1536,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.1,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    // ── anthropic（15 个 LLM）──
    {
        .id = "claude-fable-5",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 10.0,
        .price_output = 50.0,
        .price_cache_read = 1.0,
        .price_cache_write = 12.5,
    },
    {
        .id = "claude-haiku-4-5",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 1.0,
        .price_output = 5.0,
        .price_cache_read = 0.1,
        .price_cache_write = 1.25,
    },
    {
        .id = "claude-haiku-4-5-20251001",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 1.0,
        .price_output = 5.0,
        .price_cache_read = 0.1,
        .price_cache_write = 1.25,
    },
    {
        .id = "claude-opus-4-1",
        .context_window = 200000,
        .max_output_tokens = 32000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 15.0,
        .price_output = 75.0,
        .price_cache_read = 1.5,
        .price_cache_write = 18.75,
    },
    {
        .id = "claude-opus-4-1-20250805",
        .context_window = 200000,
        .max_output_tokens = 32000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 15.0,
        .price_output = 75.0,
        .price_cache_read = 1.5,
        .price_cache_write = 18.75,
    },
    {
        .id = "claude-opus-4-5",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 25.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "claude-opus-4-5-20251101",
        .context_window = 200000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 25.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "claude-opus-4-6",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "max" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 25.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "claude-opus-4-7",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 25.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "claude-opus-4-8",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 25.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "claude-opus-5",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 5.0,
        .price_output = 25.0,
        .price_cache_read = 0.5,
        .price_cache_write = 6.25,
    },
    {
        .id = "claude-sonnet-4-5",
        .context_window = 1000000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 3.0,
        .price_output = 15.0,
        .price_cache_read = 0.3,
        .price_cache_write = 3.75,
    },
    {
        .id = "claude-sonnet-4-5-20250929",
        .context_window = 1000000,
        .max_output_tokens = 64000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 3.0,
        .price_output = 15.0,
        .price_cache_read = 0.3,
        .price_cache_write = 3.75,
    },
    {
        .id = "claude-sonnet-4-6",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "max" },
        .thinking_field = {},
        .price_input = 3.0,
        .price_output = 15.0,
        .price_cache_read = 0.3,
        .price_cache_write = 3.75,
    },
    {
        .id = "claude-sonnet-5",
        .context_window = 1000000,
        .max_output_tokens = 128000,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "xhigh", "max" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 10.0,
        .price_cache_read = 0.2,
        .price_cache_write = 2.5,
    },
    // ── google（30 个 LLM）──
    {
        .id = "deep-research-max-preview-04-2026",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 12.0,
        .price_cache_read = 0.2,
        .price_cache_write = 0.0,
    },
    {
        .id = "deep-research-preview-04-2026",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 12.0,
        .price_cache_read = 0.2,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.0-flash",
        .context_window = 1048576,
        .max_output_tokens = 8192,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.1,
        .price_output = 0.4,
        .price_cache_read = 0.025,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.0-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 8192,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.075,
        .price_output = 0.3,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.5-computer-use-preview-10-2025",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 1.25,
        .price_output = 10.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.5-flash",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 0.3,
        .price_output = 2.5,
        .price_cache_read = 0.03,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.5-flash-image",
        .context_window = 32768,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 0.3,
        .price_output = 30.0,
        .price_cache_read = 0.075,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.5-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 0.1,
        .price_output = 0.4,
        .price_cache_read = 0.01,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-2.5-pro",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 1.25,
        .price_output = 10.0,
        .price_cache_read = 0.125,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3-flash-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.5,
        .price_output = 3.0,
        .price_cache_read = 0.05,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3-pro-image",
        .context_window = 131072,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "low", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 120.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3-pro-image-preview",
        .context_window = 131072,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 120.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3-pro-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "low", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 12.0,
        .price_cache_read = 0.2,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-flash-image",
        .context_window = 65536,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "minimal", "minimal", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.5,
        .price_output = 60.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-flash-image-preview",
        .context_window = 65536,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "minimal", "minimal", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.5,
        .price_output = 60.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.25,
        .price_output = 1.5,
        .price_cache_read = 0.025,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-flash-lite-image",
        .context_window = 65536,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "minimal", "minimal", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.25,
        .price_output = 30.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-flash-lite-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.25,
        .price_output = 1.5,
        .price_cache_read = 0.025,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-pro-preview",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 12.0,
        .price_cache_read = 0.2,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.1-pro-preview-customtools",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "low", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 2.0,
        .price_output = 12.0,
        .price_cache_read = 0.2,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.5-flash",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.5,
        .price_output = 9.0,
        .price_cache_read = 0.15,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.5-flash-lite",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.3,
        .price_output = 2.5,
        .price_cache_read = 0.03,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-3.6-flash",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.5,
        .price_output = 7.5,
        .price_cache_read = 0.15,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-embedding-001",
        .context_window = 2048,
        .max_output_tokens = 1,
        .reasoning = false,
        .supports_image_input = false,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.15,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-embedding-2",
        .context_window = 8192,
        .max_output_tokens = 1,
        .reasoning = false,
        .supports_image_input = true,
        .thinking_level_map = { std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt },
        .thinking_field = {},
        .price_input = 0.2,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-flash-latest",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 1.5,
        .price_output = 9.0,
        .price_cache_read = 0.15,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-flash-lite-latest",
        .context_window = 1048576,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "minimal", "low", "medium", "high", "high", "high" },
        .thinking_field = {},
        .price_input = 0.25,
        .price_output = 1.5,
        .price_cache_read = 0.025,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemini-robotics-er-1.6-preview",
        .context_window = 131072,
        .max_output_tokens = 65536,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "1024", "2048", "4096", "8192", "16384", "32768" },
        .thinking_field = {},
        .price_input = 1.0,
        .price_output = 5.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemma-4-26b-a4b-it",
        .context_window = 262144,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 0.0,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
    {
        .id = "gemma-4-31b-it",
        .context_window = 262144,
        .max_output_tokens = 32768,
        .reasoning = true,
        .supports_image_input = true,
        .thinking_level_map = { "off", "on", "on", "on", "on", "on", "on" },
        .thinking_field = {},
        .price_input = 0.0,
        .price_output = 0.0,
        .price_cache_read = 0.0,
        .price_cache_write = 0.0,
    },
};

inline constexpr BuiltinProviderTable kAllProviders[] = {
    { "deepseek", std::span<const BuiltinModel>(&kGeneratedModels[0], 4) },
    { "openai", std::span<const BuiltinModel>(&kGeneratedModels[4], 44) },
    { "anthropic", std::span<const BuiltinModel>(&kGeneratedModels[48], 15) },
    { "google", std::span<const BuiltinModel>(&kGeneratedModels[63], 30) },
};

}  // namespace agent::detail
